services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    
    env_file:
    - .env
    container_name: server_app
    restart: unless-stopped

    ports:
      - "8088:80"

    volumes:
      - ./:/var/www/html
      - vendor_data:/var/www/html/vendor

    depends_on:
      serverdb:
        condition: service_healthy
      redis:
        condition: service_healthy

  serverdb:
    image: mariadb:10.5
    container_name: serverdb
    restart: unless-stopped

    environment:
      MARIADB_DATABASE: igl_vas
      MARIADB_ROOT_PASSWORD: root

    ports:
      - "3307:3306"

    volumes:
      - dbdata:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: server_redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redisdata:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: server_phpmyadmin
    restart: unless-stopped

    ports:
      - "8081:80"

    environment:
      PMA_HOST: serverdb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 512M

    depends_on:
      serverdb:
        condition: service_healthy

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    
    env_file:
    - .env
    container_name: server_queue
    restart: unless-stopped

    command: >
      php artisan queue:work redis
      --sleep=1
      --tries=3
      --timeout=120

    volumes:
      - ./:/var/www/html
      - vendor_data:/var/www/html/vendor

    depends_on:
      serverdb:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  dbdata:
  redisdata:
  vendor_data: